### ISSUE TITLE
fixed some bugs for using cuda

### ISSUE THREAD

**Issue by kaixindelele** [sush1996/DDPG_Fetch#2]
https://github.com/kaixindelele/DDPG_Fetch

And how did you draw this multi-bar graph?
The script to draw the graph is not in this code base?

**Comment by sush1996** [comment]
If you're referring to the single plot for multiple models, I've separately saved the mean success rates in each epoch, for each mode in an array and  plotted all those in "viz.py". I've uploaded my plot data and the program for plotting it - it's not clean at the moment. But I'll get to it. Thanks for pointing out.

**Comment by kaixindelele** [comment]
Thanks, I got the viz.py.
I was going to upload two files, but I can not pull new request the new branch. 
I modified the two files：
[https://github.com/kaixindelele/DDPG_Fetch/blob/master/ddpg_agent.py](https://github.com/kaixindelele/DDPG_Fetch/blob/master/ddpg_agent.py#L143)

[https://github.com/kaixindelele/DDPG_Fetch/blob/master/models.py](https://github.com/kaixindelele/DDPG_Fetch/blob/master/models.py)
